# Generated by Django 5.2.17 on 2026-09-18 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.PositiveIntegerField(default=30)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('laboratorio', 'Laboratorio'), ('taller', 'Taller')], default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('horas_semanales', models.PositiveIntegerField(default=3)),
                ('requiere_laboratorio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semanales', models.PositiveIntegerField(default=3)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.materia')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.profesor')),
            ],
            options={
                'unique_together': {('grupo', 'materia')},
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='materias',
            field=models.ManyToManyField(through='horarios.GrupoMateria', to='horarios.materia'),
        ),
        migrations.CreateModel(
            name='SlotHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'ordering': ['dia', 'hora_inicio'],
                'unique_together': {('dia', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='horarios.profesor')),
            ],
            options={
                'unique_together': {('profesor', 'dia', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generado_automaticamente', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.aula')),
                ('grupo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='horarios.grupomateria')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.profesor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.slothorario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profesor', 'slot'), name='unique_profesor_slot'), models.UniqueConstraint(fields=('grupo_materia', 'slot'), name='unique_grupo_slot')],
            },
        ),
    ]
