# Generated by Django 5.2.17 on 2026-09-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(default='07:00')),
                ('hora_fin', models.TimeField(default='17:00')),
                ('duracion_bloque', models.PositiveIntegerField(default=60, help_text='Duración de cada bloque en minutos (ej: 60)')),
                ('dias_activos', models.CharField(default='1,2,3,4,5', help_text='Días separados por coma. Ej: 1,2,3,4,5 = Lunes a Viernes', max_length=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Horario',
                'verbose_name_plural': 'Configuración de Horario',
            },
        ),
    ]
