# Generated by Django 5.2.17 on 2026-09-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_configuracionhorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhorario',
            name='receso1_fin',
            field=models.TimeField(blank=True, help_text='Fin del primer receso (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='receso1_inicio',
            field=models.TimeField(blank=True, help_text='Inicio del primer receso (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='receso2_fin',
            field=models.TimeField(blank=True, help_text='Fin del segundo receso (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='receso2_inicio',
            field=models.TimeField(blank=True, help_text='Inicio del segundo receso (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='configuracionhorario',
            name='duracion_bloque',
            field=models.PositiveIntegerField(default=50, help_text='Duración de cada bloque en minutos (ej: 50)'),
        ),
    ]
