# Generated by Django 5.2.17 on 2026-09-21 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_configuracionhorario_receso1_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('trimestre', 'Trimestre'), ('bimestre', 'Bimestre'), ('semestre', 'Semestre'), ('cuatrimestre', 'Cuatrimestre'), ('anual', 'Anual')], default='trimestre', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='profesor',
            field=models.OneToOneField(blank=True, help_text='Solo para usuarios con rol profesor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_usuario', to='horarios.profesor'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('consulta', 'Consulta')], default='coordinador', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='horarios.grupo')),
            ],
            options={
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación de 0 a 10 (puede ser decimal)', max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='horarios.alumno')),
                ('capturada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_capturadas', to=settings.AUTH_USER_MODEL)),
                ('grupo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='horarios.grupomateria')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='horarios.periodo')),
            ],
            options={
                'ordering': ['alumno__apellido_paterno', 'grupo_materia__materia__nombre'],
                'unique_together': {('alumno', 'grupo_materia', 'periodo')},
            },
        ),
    ]
