# Generated by Django 5.2.17 on 2026-09-22 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_alter_perfilusuario_rol_alter_perfilusuario_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('retardo', 'Retardo'), ('justificado', 'Justificado')], default='presente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='horarios.alumno')),
                ('grupo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='horarios.grupomateria')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', 'alumno__apellido_paterno'],
                'unique_together': {('alumno', 'grupo_materia', 'fecha')},
            },
        ),
    ]
