# Generated by Django 5.2.17 on 2026-09-23 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_reporte', models.CharField(choices=[('conducta', 'Conducta'), ('academico', 'Académico'), ('asistencia', 'Asistencia'), ('otro', 'Otro')], default='conducta', max_length=20)),
                ('resumen', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='horarios.alumno')),
                ('grupo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='horarios.grupomateria')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha', 'alumno__apellido_paterno'],
            },
        ),
    ]
