# Generated by Django 5.2.17 on 2026-09-23 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_incidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('examen', 'Examen'), ('proyecto', 'Proyecto'), ('participacion', 'Participación'), ('practica', 'Práctica'), ('otro', 'Otro')], default='tarea', max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje que vale esta evidencia (ej: 20.00 para 20%)', max_digits=5)),
                ('fecha', models.DateField(help_text='Fecha en que se aplicó o entregó')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('grupo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='horarios.grupomateria')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='horarios.periodo')),
            ],
            options={
                'verbose_name': 'Evidencia de desempeño',
                'verbose_name_plural': 'Evidencias de desempeño',
                'ordering': ['fecha', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación de 0 a 10', max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_evidencias', to='horarios.alumno')),
                ('capturada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_evidencias_capturadas', to=settings.AUTH_USER_MODEL)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='horarios.evidenciadesempeno')),
            ],
            options={
                'ordering': ['alumno__apellido_paterno', 'evidencia__fecha'],
                'unique_together': {('evidencia', 'alumno')},
            },
        ),
    ]
