# Generated by Django 5.2.17 on 2026-09-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0009_evidenciadesempeno_calificacionevidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionevidencia',
            name='porcentaje_obtenido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje obtenido por el alumno en esta evidencia (0 al valor total de la evidencia)', max_digits=5, null=True),
        ),
    ]
