# Generated by Django 5.2.17 on 2026-09-23 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0010_calificacionevidencia_porcentaje_obtenido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planeacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título o nombre de la planeación', max_length=200)),
                ('tema', models.CharField(help_text='Tema principal', max_length=300)),
                ('objetivo', models.TextField(help_text='Objetivo general de la planeación')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del periodo a planear')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del periodo a planear')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planeaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('grupo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeaciones', to='horarios.grupomateria')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeaciones', to='horarios.periodo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeaciones', to='horarios.profesor')),
            ],
            options={
                'verbose_name': 'Planeación',
                'verbose_name_plural': 'Planeaciones',
                'ordering': ['-fecha_inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='SesionPlaneacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número de sesión (1, 2, 3...)')),
                ('fecha', models.DateField()),
                ('duracion_minutos', models.PositiveIntegerField(default=50, help_text='Duración de la sesión en minutos')),
                ('recursos', models.TextField(help_text='Recursos y materiales a usar en la sesión')),
                ('producto', models.TextField(help_text='Producto o evidencia que se espera de la sesión')),
                ('actividades', models.TextField(blank=True, help_text='Descripción de las actividades (inicio, desarrollo, cierre)', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('planeacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='horarios.planeacion')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['planeacion', 'numero'],
                'unique_together': {('planeacion', 'numero')},
            },
        ),
    ]
