# Generated by Django 5.2.17 on 2026-09-24 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0011_planeacion_sesionplaneacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Si el evento dura varios días', null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('examen', 'Examen'), ('consejo', 'Consejo Técnico'), ('evento', 'Evento escolar'), ('feriado', 'Día feriado'), ('reunion', 'Reunión'), ('suspension', 'Suspensión de clases'), ('otro', 'Otro')], default='evento', max_length=20)),
                ('todo_el_dia', models.BooleanField(default=True, help_text='Si no tiene hora específica')),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento del calendario',
                'verbose_name_plural': 'Eventos del calendario',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
