# Generated by Django 5.2.17 on 2026-09-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0012_eventocalendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='Mi Institución Educativa', help_text='Nombre oficial de la institución', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo de la institución (se usará en los PDFs)', null=True, upload_to='institucion/')),
                ('direccion', models.CharField(blank=True, help_text='Dirección de la institución', max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('ciclo_escolar', models.CharField(blank=True, help_text='Ej: 2025-2026', max_length=50, null=True)),
                ('lema', models.CharField(blank=True, help_text='Lema o misión corta de la institución', max_length=300, null=True)),
                ('director', models.CharField(blank=True, help_text='Nombre del director o responsable', max_length=200, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de la Institución',
                'verbose_name_plural': 'Configuración de la Institución',
            },
        ),
    ]
