# Generated by Django 5.2.17 on 2026-09-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0013_configuracioninstitucion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={},
        ),
        migrations.AddField(
            model_name='periodo',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='horarios.periodo'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='tipo',
            field=models.CharField(choices=[('anual', 'Año escolar'), ('trimestre', 'Trimestre'), ('periodo', 'Periodo de evaluación')], default='anual', max_length=20),
        ),
    ]
