# Generated by Django 5.2.17 on 2026-09-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0014_alter_periodo_options_periodo_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='subgrupo',
            field=models.CharField(blank=True, choices=[('1', 'Subgrupo 1'), ('2', 'Subgrupo 2'), ('', 'Sin subgrupo')], default='', help_text='Subgrupo del alumno para materias paralelas (ej: Inglés Nivel 1 vs Nivel 2)', max_length=2),
        ),
        migrations.AddField(
            model_name='grupomateria',
            name='subgrupo',
            field=models.CharField(blank=True, choices=[('', 'Todo el grupo'), ('1', 'Solo subgrupo 1'), ('2', 'Solo subgrupo 2')], default='', help_text='Si está vacío, aplica a todo el grupo. Si tiene valor, solo al subgrupo indicado.', max_length=2),
        ),
        migrations.AddField(
            model_name='materia',
            name='es_paralela',
            field=models.BooleanField(default=False, help_text='Indica que esta materia se imparte en paralelo con otra en el mismo horario'),
        ),
        migrations.AddField(
            model_name='materia',
            name='materia_padre',
            field=models.ForeignKey(blank=True, help_text='Si es una variante (ej: Inglés Nivel 1), apunta a la materia principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='horarios.materia'),
        ),
    ]
