# Generated by Django 5.2.17 on 2026-10-02 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0015_alumno_subgrupo_grupomateria_subgrupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='modulos_permitidos',
            field=models.JSONField(blank=True, default=dict, help_text='Dict de módulos permitidos: {"grupo": {"ver": true, "editar": false}, ...}'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='profesor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_usuario', to='horarios.profesor'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('consulta', 'Consulta'), ('auxiliar', 'Auxiliar Académico')], default='consulta', max_length=20),
        ),
    ]
