# Generated by Django 5.2.17 on 2026-10-03 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0016_perfilusuario_modulos_permitidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoSubgrupoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgrupo', models.CharField(choices=[('1', 'Subgrupo 1'), ('2', 'Subgrupo 2')], help_text='Subgrupo específico del alumno para esta materia', max_length=2)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_subgrupo', to='horarios.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_subgrupo', to='horarios.materia')),
            ],
            options={
                'verbose_name': 'Excepción de subgrupo por materia',
                'verbose_name_plural': 'Excepciones de subgrupo por materia',
                'ordering': ['alumno__apellido_paterno', 'alumno__apellido_materno', 'alumno__nombre', 'materia__nombre'],
                'unique_together': {('alumno', 'materia')},
            },
        ),
    ]
