# Generated by Django 5.2.17 on 2026-10-06 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0017_alumnosubgrupomateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Grupo del alumno (obligatorio para incidencias creadas por auxiliares)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='horarios.grupo'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='grupo_materia',
            field=models.ForeignKey(blank=True, help_text='Materia específica (opcional, para incidencias creadas por profesores)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='horarios.grupomateria'),
        ),
    ]
